### ISSUE TITLE
Second plot now showing up

### ISSUE THREAD

**Issue by asiv** [jkaupp/easel#4]
If you arrive at a terminal branch (at Level 4 for example) and Undo Selections and then try move through a branch that gets past that point (like moving to Level 5), the interface does not display the next drop down. 

If you go to a terminal branch at a higher level (say Level 6) and then go to a lower terminal brach, the lower terminal branch will display correctly. But then it creates the same problem again. So you will not be able to get to that higher level branch again. 

Current solution is just to refresh the whole session.

**Comment by jkaupp** [comment]
Bug was related to using the `$` accessor in the inputs.  Changed the filtering to use `[[` instead.

**Comment by jkaupp** [comment]
This bug was occurring for a few reasons:
1. `Isolate` statements were not properly used to wrap the logical comparison of `plot_flag`.
2. Position of the `q#_data` was changed to execute on level generation
3. Improper sequencing of `if` statements locked out the conditions after the first plot had been shown.

These were fixed in a separate branch and merged into the master. Application is updated on the shiny server
